## Crypto

### 1. Read Data

In [1]:
import sys, os, glob
import pandas as pd

In [2]:
REL_PATH = "../data/raw/*.csv"
files = list()

for file in glob.glob(REL_PATH):
    print(file)
    df = pd.read_csv(file, index_col=None, header=0)
    files.append(df)

../data/raw\bitcoin_cash_price.csv
../data/raw\bitcoin_dataset.csv
../data/raw\bitcoin_price.csv
../data/raw\bitconnect_price.csv
../data/raw\dash_price.csv
../data/raw\ethereum_classic_price.csv
../data/raw\ethereum_dataset.csv
../data/raw\ethereum_price.csv
../data/raw\iota_price.csv
../data/raw\litecoin_price.csv
../data/raw\monero_price.csv
../data/raw\nem_price.csv
../data/raw\neo_price.csv
../data/raw\numeraire_price.csv
../data/raw\omisego_price.csv
../data/raw\qtum_price.csv
../data/raw\ripple_price.csv
../data/raw\stratis_price.csv
../data/raw\waves_price.csv

In [3]:
data = pd.concat(files, axis=0, ignore_index=True)

In [4]:
data.head()

,Date,Open,High,Low,Close,Volume,Market Cap,btc_market_price,btc_total_bitcoins,btc_market_cap,...,eth_blocks,eth_uncles,eth_blocksize,eth_blocktime,eth_gasprice,eth_gaslimit,eth_gasused,eth_ethersupply,eth_chaindatasize,eth_ens_register
0,"Sep 05, 2017",514.90,550.95,458.78,541.71,"338,978,000","8,527,100,000",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Sep 04, 2017",608.26,608.26,500.75,517.24,"328,957,000","10,072,200,000",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Sep 03, 2017",578.27,617.41,563.59,607.43,"344,862,000","9,574,520,000",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Sep 02, 2017",621.96,642.05,560.58,575.90,"350,478,000","10,297,000,000",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Sep 01, 2017",588.40,645.52,586.73,622.17,"393,839,000","9,740,460,000",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN